[package]
name = "serve-directory"
version = "0.1.0"
authors = ["Joseph Skubal"]
edition = "2018"
repository = "https://gitlab.com/skubalj/serve-directory"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build_html = "1.0.0"
tokio = { version = "1.1.0", features = ["full"] }
warp = "0.3.0"